edition = "2021"
max_width = 100
newline_style = "Unix"
reorder_imports = true
use_small_heuristics = "Max"

# 稳定后取消注释
#condense_wildcard_suffixes = true
#format_macro_matchers = true
#group_imports = "StdExternalCrate"
#imports_granularity = "Crate"
#normalize_comments = true
#report_fixme = "Unnumbered"
#report_todo = "Unnumbered"
#wrap_comments = true
